/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Perfil` | `/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/conversas` | `/conversas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/feed` | `/feed`; params?: Router.UnknownInputParams; } | { pathname: `/SubTelas/camera`; params?: Router.UnknownInputParams; } | { pathname: `/SubTelas/chat`; params?: Router.UnknownInputParams; } | { pathname: `/SubTelas/contrato_anuncio`; params?: Router.UnknownInputParams; } | { pathname: `/SubTelas/perfil_outros`; params?: Router.UnknownInputParams; } | { pathname: `/SubTelas/pix`; params?: Router.UnknownInputParams; } | { pathname: `/SubTelas/post_details`; params?: Router.UnknownInputParams; } | { pathname: `/SubTelas/telapix`; params?: Router.UnknownInputParams; } | { pathname: `/utils/firebaseQueries`; params?: Router.UnknownInputParams; } | { pathname: `/utils/imageCache`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Perfil` | `/Perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/conversas` | `/conversas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/feed` | `/feed`; params?: Router.UnknownOutputParams; } | { pathname: `/SubTelas/camera`; params?: Router.UnknownOutputParams; } | { pathname: `/SubTelas/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/SubTelas/contrato_anuncio`; params?: Router.UnknownOutputParams; } | { pathname: `/SubTelas/perfil_outros`; params?: Router.UnknownOutputParams; } | { pathname: `/SubTelas/pix`; params?: Router.UnknownOutputParams; } | { pathname: `/SubTelas/post_details`; params?: Router.UnknownOutputParams; } | { pathname: `/SubTelas/telapix`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/firebaseQueries`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/imageCache`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Perfil${`?${string}` | `#${string}` | ''}` | `/Perfil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/conversas${`?${string}` | `#${string}` | ''}` | `/conversas${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/feed${`?${string}` | `#${string}` | ''}` | `/feed${`?${string}` | `#${string}` | ''}` | `/SubTelas/camera${`?${string}` | `#${string}` | ''}` | `/SubTelas/chat${`?${string}` | `#${string}` | ''}` | `/SubTelas/contrato_anuncio${`?${string}` | `#${string}` | ''}` | `/SubTelas/perfil_outros${`?${string}` | `#${string}` | ''}` | `/SubTelas/pix${`?${string}` | `#${string}` | ''}` | `/SubTelas/post_details${`?${string}` | `#${string}` | ''}` | `/SubTelas/telapix${`?${string}` | `#${string}` | ''}` | `/utils/firebaseQueries${`?${string}` | `#${string}` | ''}` | `/utils/imageCache${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Perfil` | `/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/conversas` | `/conversas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/feed` | `/feed`; params?: Router.UnknownInputParams; } | { pathname: `/SubTelas/camera`; params?: Router.UnknownInputParams; } | { pathname: `/SubTelas/chat`; params?: Router.UnknownInputParams; } | { pathname: `/SubTelas/contrato_anuncio`; params?: Router.UnknownInputParams; } | { pathname: `/SubTelas/perfil_outros`; params?: Router.UnknownInputParams; } | { pathname: `/SubTelas/pix`; params?: Router.UnknownInputParams; } | { pathname: `/SubTelas/post_details`; params?: Router.UnknownInputParams; } | { pathname: `/SubTelas/telapix`; params?: Router.UnknownInputParams; } | { pathname: `/utils/firebaseQueries`; params?: Router.UnknownInputParams; } | { pathname: `/utils/imageCache`; params?: Router.UnknownInputParams; };
    }
  }
}
